apiVersion: apps/v1
kind: Deployment
metadata:
    name: testci
    labels:
        app: testci
spec:
    replicas: 1
    selector:
        matchLabels:
            app: testci
    template:
        metadata:
            labels:
                app: testci
            annotations:
                app.kubernetes.io/redeploy-timestamp: '2024-05-15T13:24:00Z' # ← sera remplacée dynamiquement
        spec:
            containers:
                - name: testci
                  image: ghcr.io/synerraphael/testci:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
