apiVersion: v1
kind: Service
metadata:
  name: testci
spec:
  type: NodePort   # ✅ au lieu de LoadBalancer
  selector:
    app: testci
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # facultatif, ou laisse Kubernetes en choisir un