name: CI - Go Project

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'

            - name: Install golangci-lint
              run: |
                  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

            - name: Run golangci-lint
              run: golangci-lint run ./...

            - name: Install dependencies
              run: go mod tidy

            - name: Build
              run: go build -v ./...

            - name: Run tests
              run: go test ./...

            - name: Build binary
              run: go build -o myapp .

            - name: Upload binary
              uses: actions/upload-artifact@v4
              with:
                  name: myapp-binary
                  path: .

            - name: Check formatting
              run: test -z "$(gofmt -l .)"

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ghcr.io/synerraphael/testci:latest
            - name: Update deployment.yaml with new tag
              run: |
                  TAG=${GITHUB_SHA::7}
                  sed -i "s|ghcr.io/synerraphael/testci:.*|ghcr.io/synerraphael/testci:$TAG|g" k8s/deployment.yml
                  git config user.name "CI Bot"
                  git config user.email "ci@yourdomain.com"
                  git add k8s/deployment.yaml
                  git commit -m "ci: update image tag to $TAG"
                  git push
