name : CI - Go Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v2.1.0  # adapte à la dernière version stable

        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'

        - name: Install dependencies
          run: go mod tidy

        - name: Build
          run: go build -v ./...

        - name: Run tests
          run: go test ./...